return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.7.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 212,
  height = 15,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 124,
  backgroundcolor = { 107, 140, 255 },
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "assets/graphics/tiles.png",
      imagewidth = 256,
      imageheight = 224,
      backgroundcolor = { 255, 0, 255 },
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 224,
      tiles = {
        {
          id = 3,
          properties = {
            ["collidable"] = true
          }
        }
      }
    },
    {
      name = "sprites",
      firstgid = 225,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "assets/graphics/sprites.png",
      imagewidth = 256,
      imageheight = 256,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 256,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 212,
      height = 15,
      id = 1,
      name = "Background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztlVsOgkAMRSf++dqtrx/9dy/qCtQVKDtgL9YEkqbOo2QaRsd7khsSwrRngIJzAAAAQN2cKGfKxaBGbp2c3rl9S+0B/nbux4y1KbT7vFJulLuiVmjPfY1UHS1DnlHKP+Uu61jsAf6ftWL+Vu6tp6/Vt0UzJ0NrWc6Mpt8vuvOe8B/Xn8+T5R4A+Efa9CUAACWYJwDswDwBYIdvnmbiCADQ4ZunZXecK9bvDF1KAP+y1OYv5+n9T5qyxP5Ra8qGsjVyGRv4l6VGfzlPky4Lz3ru39faU1Yufk8elCdLE3CR1zeRmhp4X1mrJv/UO1nK37GeEnn/hzCmfwjt+9PP04GdS/kDAAAA38ILCyefPQ=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Sprites",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "flag",
          type = "",
          shape = "rectangle",
          x = 3159,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 313,
          visible = true,
          properties = {
            ["collision"] = "cross"
          }
        },
        {
          id = 50,
          name = "mario",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 321,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 328,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 644,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 844,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 864,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 1260,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 1304,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 1520,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 1544,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 1976,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 2000,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 2028,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 2052,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 2772,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "goomba",
          shape = "rectangle",
          x = 2796,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 231,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "koopa",
          shape = "rectangle",
          x = 1692,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 2147483903,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "mushroom",
          shape = "rectangle",
          x = 336,
          y = 156,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 385,
          visible = true,
          properties = {
            ["collision"] = "cross",
            ["ref"] = 1
          }
        },
        {
          id = 67,
          name = "",
          type = "up",
          shape = "rectangle",
          x = 1024,
          y = 140,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 386,
          visible = true,
          properties = {
            ["collision"] = "cross",
            ["ref"] = 2
          }
        },
        {
          id = 68,
          name = "",
          type = "mushroom",
          shape = "rectangle",
          x = 1248,
          y = 156,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 385,
          visible = true,
          properties = {
            ["collision"] = "cross",
            ["ref"] = 3
          }
        },
        {
          id = 70,
          name = "",
          type = "mushroom",
          shape = "rectangle",
          x = 1744,
          y = 92,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 385,
          visible = true,
          properties = {
            ["collision"] = "cross",
            ["ref"] = 4
          }
        },
        {
          id = 71,
          name = "pipedown",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 152,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "pipeup",
          type = "",
          shape = "rectangle",
          x = 2608,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 152,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "castleflag",
          type = "",
          shape = "rectangle",
          x = 3264,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 394,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "Foreground",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 75,
          name = "",
          type = "walltop",
          shape = "rectangle",
          x = 3264,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 3264,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 3280,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 3280,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1744,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {
            ["ref"] = 4
          }
        },
        {
          id = 80,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1696,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1744,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1792,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1616,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1504,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 336,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {
            ["ref"] = 1
          }
        },
        {
          id = 87,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 368,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 352,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1024,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {
            ["invisible"] = true,
            ["ref"] = 2
          }
        },
        {
          id = 90,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 1248,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {
            ["ref"] = 3
          }
        },
        {
          id = 91,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 2064,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 2080,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "block",
          shape = "rectangle",
          x = 2720,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 320,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 352,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 384,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1232,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1264,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1280,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1296,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1312,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1328,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1344,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1360,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1376,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1392,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1456,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1472,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1488,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1504,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {
            ["coins"] = true
          }
        },
        {
          id = 111,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1600,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1888,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1968,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1952,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 1936,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 2048,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 2096,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 2064,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 2080,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 2688,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 2704,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "brick",
          shape = "rectangle",
          x = 2736,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 212,
      height = 15,
      id = 2,
      name = "Collisions",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {
        ["collidable"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1kEOgjAQheFiekG9gd7/ELKQRGg7M9pXjPB/ySQsOrMo8wIpAQAAAAAAABglvwpAn5zIE6CQE3kCFLZZIk+l61y3AWdRyo3nSN+3vSq1LJ0xT14G7nM9grM+OYu1WiYi+1jb3b13uZWlI+Up+q3wMkCexrMyYe1ka3e93t7/iPd+K0uKPF0EMxSiu02efiuSidpeWrvr9fa+p6Xfy1L0+2pp5WmiilLcDXesvU/qf2uhmNE75wh1pnt4AvsdDzY="
    }
  }
}
